// packages/react/src/routes/channel/ChannelAbout.tsx
import { useOutletContext } from "react-router-dom";
import { ChannelOutletContext } from "../channel";
import { useTranslation } from "react-i18next";

export default function ChannelAbout() {
  const { t } = useTranslation();
  const { channel } = useOutletContext<ChannelOutletContext>();

  return (
    <div className="container flex gap-4 py-4 max-sm:flex-col-reverse">
      <div className="bg-base-3 w-full whitespace-pre-wrap rounded-lg p-4">
        {channel.description}
      </div>
      <div className="bg-base-3 divide-base-5 h-fit w-full shrink-0 flex-col divide-y-2 rounded-lg p-4 md:w-80 [&>p]:py-2">
        <h3 className="pb-2 text-xl font-bold">
          {t("component.channelInfo.stats")}
        </h3>
        <p>
          {t("component.channelInfo.videoCount", {
            0: Number(channel.video_count).toLocaleString(),
          })}
        </p>
        <p>
          {t("component.channelInfo.clipCount", {
            n: Number(channel.clip_count).toLocaleString(),
          })}
        </p>
        <p>
          {Number(channel.view_count).toLocaleString()}
          {t("component.channelInfo.totalViews")}
        </p>
      </div>
    </div>
  );
}

// src/views/channel_views/ChannelAbout.vue
<template>
    <v-container>
        <v-row>
            <v-col sm="12" class="col-12 col-md-3">
                <strong>{{ $t("component.channelInfo.stats") }}</strong>
                <v-divider class="my-3" />
                {{ $t("component.channelInfo.videoCount", [channel.video_count]) }}
                <v-divider class="my-3" />
                {{ channel.clip_count }} {{ $t("component.channelInfo.clipCount", [channel.clip_count]) }}
                <v-divider class="my-3" />
                {{ channel.view_count }} {{ $t("component.channelInfo.totalViews") }}
                <v-divider class="my-3" />
            </v-col>
            <v-col style="white-space: pre-wrap" class="col-12 col-md-9" order="md-first">
                <strong>{{ $t("component.videoDescription.description") }}</strong>
                <br>
                <div v-linkified v-html="channel.description" />
            </v-col>
        </v-row>
    </v-container>
</template>

<script lang="ts">
export default {
    name: "ChannelAbout",
    computed: {
        channel() {
            return this.$store.state.channel.channel;
        },
    },
};
</script>

<style></style>
