// packages/react/src/components/channel/ChannelImg.tsx
import { cn, getChannelPhoto } from "@/lib/utils";

export function ChannelImg({
  channelId,
  size = 100,
  className,
}: {
  channelId: string;
  size?: number;
  className?: string;
}) {
  return (
    <img
      loading="lazy"
      className={cn("rounded-full shrink-0", className)}
      src={getChannelPhoto(channelId, size)}
    />
  );
}

// src/components/ChannelImg.vue
<template>
    <v-img :src="photo"></v-img>
</template>

<script>
import { channel_photo_resize } from "@/utils/image-utils";
export default {
    name: "ChannelImg",
    props: {
        src: {
            type: String,
            required: true,
            default: "",
        },
        size: {
            type: Number,
            default: 40,
        },
    },
    computed: {
        photo() {
            return channel_photo_resize(this.src, this.size);
        },
    },
};
</script>

<style></style>
