// packages/vue3/src/components/tldex/new-editor/components/DraggableNumber.vue
<template>
  <span
    :class="[horizontal ? 'cursor-col-resize' : 'cursor-row-resize']"
    @mousedown="start"
  >
    {{ rendered }}
  </span>
</template>

<script lang="ts" setup>
import xss from "xss";

const modelValue = defineModel<number>({ required: true });
const props = withDefaults(
  defineProps<{
    formatter?: (n: number) => string;
    precision?: number;
    negativeOk?: boolean;
    scale?: number;
    vertical?: boolean;
    horizontal?: boolean;
  }>(),
  {
    formatter: (x: number) => x.toString(),
    precision: 1,
    negativeOk: false,
    scale: 0.1,
    vertical: false,
    horizontal: true,
  }
);

const dragStartPos = ref<number>();
const dragInProgressValue = ref(modelValue.value);

const rendered = computed(() => {
  return props.formatter(
    dragStartPos.value == undefined
      ? modelValue.value
      : +dragInProgressValue.value.toFixed(props.precision)
  );
});
function start(e: MouseEvent) {
  dragStartPos.value = 0;
  dragInProgressValue.value = modelValue.value;
  (e.target as HTMLElement).requestPointerLock();
  (e.target as HTMLElement).style.cursor = "crosshair";

  const mouseMoveHandler = (moveEvent: MouseEvent) => {
    const movement = props.horizontal
      ? moveEvent.movementX
      : -moveEvent.movementY;
    dragStartPos.value = (dragStartPos.value ?? 0) + movement;
    const newValue = modelValue.value + dragStartPos.value * props.scale;
    console.log(
      modelValue.value,
      "+",
      dragStartPos.value * props.scale,
      "=",
      newValue
    );
    dragInProgressValue.value = props.negativeOk
      ? newValue
      : Math.max(0, newValue);
  };
  const mouseUpHandler = () => {
    document.removeEventListener("mousemove", mouseMoveHandler);
    document.removeEventListener("mouseup", mouseUpHandler);
    modelValue.value = +dragInProgressValue.value.toFixed(props.precision);
    dragStartPos.value = undefined;
    (e.target as HTMLElement).style.cursor = props.horizontal
      ? "col-resize"
      : "row-resize";
    document.exitPointerLock();
  };

  document.addEventListener("mousemove", mouseMoveHandler);
  document.addEventListener("mouseup", mouseUpHandler);
}
</script>

// packages/react/src/components/edit/DraggableNumber.tsx
import React, { useState, useEffect, useCallback } from "react";

interface DraggableNumberProps {
  value: number;
  onChange: (newValue: number) => void;
  formatter?: (n: number) => string;
  precision?: number;
  negativeOk?: boolean;
  scale?: number;
  horizontal?: boolean;
}

const DraggableNumber = ({
  value, // This should be passed as a prop from the parent component
  onChange, // This replaces the emit functionality to communicate changes back to the parent
  formatter = (x) => x.toString(),
  precision = 1,
  negativeOk = false,
  scale = 0.1,
  horizontal = true,
}: DraggableNumberProps) => {
  const [dragStartPos, setDragStartPos] = useState<number | null>(null);
  const [dragInProgressValue, setDragInProgressValue] = useState(value);

  const rendered =
    dragStartPos == null
      ? formatter(value)
      : formatter(+dragInProgressValue.toFixed(precision));

  const start = useCallback(
    (e: React.MouseEvent<HTMLSpanElement>) => {
      setDragStartPos(0);
      setDragInProgressValue(value);
      if ((e.target as HTMLSpanElement)?.style) {
        (e.target as HTMLSpanElement).style.cursor = "crosshair";
      }
      document.body.requestPointerLock();

      function mouseMoveHandler(moveEvent: MouseEvent) {
        const movement = horizontal
          ? moveEvent.movementX
          : -moveEvent.movementY;
        setDragStartPos((prevPos) => (prevPos ?? 0) + movement);
        const newValue = value + (dragStartPos ?? 0) * scale;
        setDragInProgressValue(negativeOk ? newValue : Math.max(0, newValue));
      }

      const mouseUpHandler = () => {
        document.removeEventListener("mousemove", mouseMoveHandler);
        document.removeEventListener("mouseup", mouseUpHandler);
        onChange(+dragInProgressValue.toFixed(precision));
        setDragStartPos(null);
        if ((e.target as HTMLSpanElement)?.style) {
          (e.target as HTMLSpanElement).style.cursor = horizontal
            ? "col-resize"
            : "row-resize";
        }
        document.exitPointerLock();
      };

      document.addEventListener("mousemove", mouseMoveHandler);
      document.addEventListener("mouseup", mouseUpHandler);
    },
    [
      value,
      horizontal,
      precision,
      scale,
      negativeOk,
      onChange,
      dragStartPos,
      dragInProgressValue,
    ],
  );

  useEffect(() => {
    setDragInProgressValue(value);
  }, [value]);

  const className = horizontal ? "cursor-col-resize" : "cursor-row-resize";

  return (
    <span className={className} onMouseDown={start}>
      {rendered}
    </span>
  );
};

export default DraggableNumber;
