// packages/react/src/components/common/TwitterFeed.tsx
import { DetailedHTMLProps, HTMLAttributes, useEffect, useRef } from "react";
import { useScript } from "usehooks-ts";

declare global {
  // eslint-disable-next-line
  var twttr: any;
}

const html = `<a class="twitter-timeline" data-dnt="true" data-height="400" data-width="${Math.min(
  window.innerWidth - 40,
  800,
)}" href="https://twitter.com/holodex?ref_src=twsrc%5Etfw">Tweets by Holodex</a>`;

export function TwitterFeed(
  props: DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>,
) {
  const ref = useRef<HTMLDivElement>(null);
  const status = useScript("https://platform.twitter.com/widgets.js");

  useEffect(() => {
    if (status === "ready") window.twttr?.widgets.load();
  }, [status]);

  return (
    <div {...props} ref={ref} dangerouslySetInnerHTML={{ __html: html }} />
  );
}

// src/components/common/TwitterFeed.vue
<template>
    <!-- <div class="ma-auto"> -->
    <a
        class="twitter-timeline"
        data-dnt="true"
        :data-height="$store.state.isMobile ? '410' : '410'"
        :data-theme="$vuetify.theme.dark ? 'dark' : 'light'"
        href="https://twitter.com/holodex?ref_src=twsrc%5Etfw"
    >
        Tweets by @holodex
    </a>
    <!-- </div> -->
</template>
<script lang="ts">
export default {
    mounted() {
        // TODO(jprochazk): declare this in globals.d.ts
        const w = window as any;
        if (!w.twttr) {
            const externalScript = document.createElement("script");
            externalScript.setAttribute("src", "https://platform.twitter.com/widgets.js");
            externalScript.setAttribute("async", "true");
            document.head.appendChild(externalScript);
        } else {
            w.twttr.widgets.load();
        }
    },
};
</script>

<style></style>
