// packages/react/src/components/channel/ChannelCard.tsx
import { formatCount } from "@/lib/time";
import { useFavoriteMutation, useFavorites } from "@/services/user.service";
import { Badge } from "@/shadcn/ui/badge";
import { Button } from "@/shadcn/ui/button";
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type WithNonOptional<T, NonOptionalKeys extends keyof T> = Pick<
  T,
  NonOptionalKeys
> &
  Partial<Omit<T, NonOptionalKeys>>;
type PartialChannel = WithNonOptional<
  Channel,
  "id" | "name" | "photo" | "subscriber_count" | "video_count"
>;

interface ChannelCardProps extends PartialChannel {}

export function ChannelCard({
  id,
  name,
  photo,
  subscriber_count,
  video_count,
  clip_count,
  top_topics,
  twitter,
  twitch, // inactive,
}: ChannelCardProps) {
  const { t } = useTranslation();
  const { mutate, isPending: mutateLoading } = useFavoriteMutation();
  const { data } = useFavorites();
  const isInFavorite = useMemo(
    () => data?.some((channel) => id === channel.id),
    [data, id],
  );

  console.log(name, photo);
  return (
    // Set min-height because react-virtuoso will break if the height is not fixed
    <div className="flex h-full min-h-[24rem] w-full flex-col items-center gap-2 rounded-md bg-base-3 p-4">
      <img
        className="-z-0 -mb-36 mt-4 h-32 w-32 rounded-full opacity-20 blur-2xl saturate-150"
        src={photo ?? ""}
      />
      <img className="z-10 h-24 w-24 rounded-full" src={photo ?? ""} />
      <div className="z-10 line-clamp-2 text-center text-lg font-bold">
        {name}
      </div>
      <div className="flex flex-col items-center">
        <div className="whitespace-nowrap text-sm text-base-11">
          {t("component.channelInfo.subscriberCount", {
            n: formatCount(subscriber_count ?? "0"),
          })}
        </div>
        <div className="flex flex-wrap justify-center gap-x-1 gap-y-0 text-sm text-base-11">
          <span className="whitespace-nowrap">
            {t("component.channelInfo.videoCount", { 0: video_count ?? 0 })}
          </span>
          <span>/</span>
          <span className="whitespace-nowrap">
            {t("component.channelInfo.clipCount", { n: clip_count ?? "0" })}
          </span>
        </div>
      </div>
      {top_topics && (
        <Badge variant="outline" className="capitalize">
          {top_topics[0]}
        </Badge>
      )}
      <div className="flex grow" />
      <Button
        className="w-full"
        variant={isInFavorite ? "outline" : "secondary"}
        disabled={mutateLoading}
        onClick={() => {
          mutate([
            {
              op: isInFavorite ? "remove" : "add",
              channel_id: id,
            },
          ]);
          console.log(isInFavorite);
        }}
      >
        {isInFavorite ? (
          <div className="i-heroicons:heart-solid" />
        ) : (
          <div className="i-heroicons:heart" />
        )}
        {isInFavorite
          ? t("component.channelSocials.removeFromFavorites")
          : t("component.channelSocials.addToFavorites")}
      </Button>
      <div className="flex w-full gap-2">
        <Button
          asChild
          className="w-full text-[#282828] dark:text-white"
          variant="ghost"
          size="icon-lg"
        >
          {/* Youtube Logo needs to conform with YT guidelines https://www.youtube.com/howyoutubeworks/resources/brand-resources/#logos-icons-and-colors */}
          <Link to={`https://www.youtube.com/channel/${id}`} target="_blank">
            <div className="i-mdi:youtube" />
          </Link>
        </Button>
        {twitter && (
          <Button asChild className="w-full" variant="ghost" size="icon-lg">
            <Link to={`https://x.com/${twitter}`} target="_blank">
              <div className="i-lucide:twitter" />
            </Link>
          </Button>
        )}
        {twitch && (
          <Button asChild className="w-full" variant="ghost" size="icon-lg">
            <Link to={`https://twitch.tv/${twitch}`} target="_blank">
              <div className="i-lucide:twitch" />
            </Link>
          </Button>
        )}
      </div>
    </div>
  );
}

// packages/vue3/src/components/channel/common/ChannelCard.vue
<template>
  <component
    :is="noLink ? 'div' : 'router-link'"
    class="flex flex-row items-center overflow-hidden rounded-md channel-card justify-self-auto"
    :class="slim ? '' : 'h-50'"
    :to="`/channel/${channel.id}`"
  >
    <div class="flex-shrink-0 indicator">
      <span
        v-if="live"
        class="mb-4 mr-4 indicator-item indicator-bottom live-indicator"
      ></span>
      <span
        v-else-if="$slots.default"
        class="mb-3 text-white right-5 indicator-item live-indicator indicator-bottom bg-slate-500 text-2xs"
        ><slot></slot
      ></span>

      <channel-img
        :channel="channel"
        :size="slim ? 44 : 100"
        class="m-2"
        :class="imgClass"
      />
    </div>
    <div
      class="flex-grow"
      :class="{ 'opacity-40': channel.inactive, 'ml-2': !slim }"
    >
      <span class="text-xs text-neutral opacity-60"
        ><b>{{
          channel.org ||
          (channel.type === "subber" && $t("views.channels.tabs.Subber")) ||
          "???"
        }}</b>
        {{ group ? "/ " + group : "" }}
      </span>
      <span class="-mt-1 line-clamp-1" :class="{ 'text-lg': !slim }">
        {{ preferredName }}
      </span>
      <span v-if="!slim" class="text-sm line-clamp-1 text-neutral">
        {{ subscribers }} •
        {{ $t("component.channelInfo.videoCount", [channel.video_count]) }}
        {{
          channel.clip_count &&
          " • " +
            $t("component.channelInfo.clipCount", { n: channel.clip_count })
        }}
      </span>
      <div
        v-if="channel.top_topics && !slim"
        class="opacity-60 hover:opacity-100"
      >
        <div class="inline-block text-lg align-middle i-uil:award"></div>
        <div
          v-for="t in channel.top_topics"
          :key="channel.id + 't' + t"
          class="inline-block ml-1 font-bold h-[1.1rem] leading-4 align-middle rounded cursor-pointer text-bold badge badge-sm badge-outline border-slate-600 hover:badge-accent hover:badge-outline"
        >
          {{ formatTopic(t) }}
        </div>
      </div>
    </div>
    <slot name="buttons"></slot>
    <div v-if="!slim && !$slots.buttons" class="flex flex-col h-full gap-1">
      <a
        class="c-card-icon hover:text-red-500"
        :href="`https://youtube.com/channel/${channel.id}`"
        target="_blank"
        title="Youtube"
      >
        <div :class="icons.youtube"></div>
      </a>
      <a
        class="c-card-icon hover:text-cyan-500"
        :class="{ 'btn-disabled bg-inherit opacity-20': !channel.twitter }"
        :href="channel.twitter ? `https://twitter.com/${channel.twitter}` : '#'"
        target="_blank"
        title="Twitter"
      >
        <div :class="icons.twitter"></div>
      </a>
      <button
        class="c-card-icon"
        :title="
          isFav
            ? $t('component.channelSocials.removeFromFavorites')
            : $t('component.channelSocials.addToFavorites')
        "
        @click.prevent.stop="favChannel"
      >
        <div
          :class="isFav ? 'i-mdi:heart text-red-500' : 'i-mdi:heart-outline'"
        ></div>
      </button>
    </div>
  </component>
</template>
<script lang="ts">
import { useChannelPreferredName } from "@/hooks/common/useChannelService";
import {
  useFavoritesListByID,
  useFavoritesPatcher,
} from "@/services/favorites";
import { useLangStore } from "@/stores";
import { formatCount, formatTopic } from "@/utils/functions";
import { PropType } from "vue";

export default defineComponent({
  props: {
    channel: {
      type: Object as PropType<FullChannel>,
      required: true,
    },
    variant: {
      type: String as PropType<"card" | "list">,
      default: "card",
    },
    live: Boolean,
    slim: Boolean,
    noLink: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const { preferredName } = useChannelPreferredName(props.channel);
    const lang = useLangStore();
    const fav = useFavoritesListByID();

    const isFav = computed(() => fav.value?.has(props.channel.id));
    const favPatcher = useFavoritesPatcher();
    return { preferredName, lang, isFav, favPatcher };
  },
  computed: {
    subscribers() {
      return this.channel.subscriber_count
        ? formatCount(this.channel.subscriber_count, this.lang.lang)
        : "";
    },
    imgClass() {
      return {
        "opacity-40": this.channel.inactive,
      };
    },
    group() {
      return this.channel.group || this.channel.suborg?.slice(2);
    },
  },
  methods: {
    formatTopic,
    favChannel() {
      this.favPatcher.mutateAsync([
        {
          op: this.isFav ? "remove" : "add",
          channel_id: this.channel.id,
          channelTemp: this.channel,
        },
      ]);
    },
  },
});
</script>
<style lang="scss">
.c-card-icon {
  @apply pr-2 btn btn-ghost rounded-sm flex-grow;

  width: 2.5rem;
  min-height: 20px;
  height: 1.5em;
  padding: 0;
  line-height: 1.4em;
  font-weight: 600;
  font-size: 1.4rem;
  opacity: 0.5;
}

.channel-card:hover {
  .c-card-icon {
    opacity: 1;
  }
}

.live-indicator {
  @apply bg-red-500 border-transparent badge badge-xs outline outline-4 outline-bgColor;
}
</style>
